-- MySQL Script generated by MySQL Workbench
-- Wed Oct 18 21:23:15 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema SWP_SHT
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema SWP_SHT
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `SWP_SHT` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema sht_swp
-- -----------------------------------------------------
USE `SWP_SHT` ;

-- -----------------------------------------------------
-- Table `SWP_SHT`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SWP_SHT`.`user` (
  `user_id` BIGINT(100) NOT NULL,
  `user_name` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `fullname` NVARCHAR(100) NULL,
  `phone` VARCHAR(45) NULL,
  `gmail` VARCHAR(45) NULL,
  `dob` DATE NULL,
  `cccd` VARCHAR(45) NULL,
  `role` INT NULL,
  `address` NVARCHAR(200) NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SWP_SHT`.`wishlist`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SWP_SHT`.`wishlist` (
  `list_id` INT NOT NULL,
  `content` NVARCHAR(200) NULL,
  `star` INT NULL,
  `user_id` BIGINT(100) NOT NULL,
  PRIMARY KEY (`list_id`),
  INDEX `fk_wishlist_user1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_wishlist_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `SWP_SHT`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SWP_SHT`.`type_of_district`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SWP_SHT`.`type_of_district` (
  `district_id` INT NOT NULL,
  `type` NVARCHAR(45) NULL,
  PRIMARY KEY (`district_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SWP_SHT`.`type_of_room`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SWP_SHT`.`type_of_room` (
  `type_id` INT NOT NULL,
  `type` NVARCHAR(45) NULL,
  PRIMARY KEY (`type_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SWP_SHT`.`post`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SWP_SHT`.`post` (
  `id_post` BIGINT(100) NOT NULL,
  `user_id` BIGINT(100) NOT NULL,
  `list_id` INT NOT NULL,
  `district_id` INT NOT NULL,
  `type_id` INT NOT NULL,
  `title` NVARCHAR(200) NULL,
  `price` INT NULL,
  `tag` VARCHAR(45) NULL,
  `status` INT NULL,
  `date_start` DATE NULL,
  `create_at` DATE NULL,
  `update_at` DATE NULL,
  `description` NVARCHAR(200) NULL,
  PRIMARY KEY (`id_post`),
  INDEX `fk_post_user_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_post_wishlist1_idx` (`list_id` ASC) VISIBLE,
  INDEX `fk_post_type_of_district1_idx` (`district_id` ASC) VISIBLE,
  INDEX `fk_post_type_of_room1_idx` (`type_id` ASC) VISIBLE,
  CONSTRAINT `fk_post_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `SWP_SHT`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_post_wishlist1`
    FOREIGN KEY (`list_id`)
    REFERENCES `SWP_SHT`.`wishlist` (`list_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_post_type_of_district1`
    FOREIGN KEY (`district_id`)
    REFERENCES `SWP_SHT`.`type_of_district` (`district_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_post_type_of_room1`
    FOREIGN KEY (`type_id`)
    REFERENCES `SWP_SHT`.`type_of_room` (`type_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SWP_SHT`.`appointment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SWP_SHT`.`appointment` (
  `appointment_id` INT NOT NULL,
  `time_start` DATE NULL,
  `user_user_id` BIGINT(100) NOT NULL,
  `post_id_post` BIGINT(100) NOT NULL,
  PRIMARY KEY (`appointment_id`),
  INDEX `fk_appointment_user1_idx` (`user_user_id` ASC) VISIBLE,
  INDEX `fk_appointment_post1_idx` (`post_id_post` ASC) VISIBLE,
  CONSTRAINT `fk_appointment_user1`
    FOREIGN KEY (`user_user_id`)
    REFERENCES `SWP_SHT`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_appointment_post1`
    FOREIGN KEY (`post_id_post`)
    REFERENCES `SWP_SHT`.`post` (`id_post`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SWP_SHT`.`proccess_booking`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SWP_SHT`.`proccess_booking` (
  `id` INT NOT NULL,
  `proccess_bookingcol` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SWP_SHT`.`payment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SWP_SHT`.`payment` (
  `id` INT NOT NULL,
  `type` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SWP_SHT`.`booking`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SWP_SHT`.`booking` (
  `id_booking` INT NOT NULL,
  `create_at` DATE NULL,
  `update_at` DATE NULL,
  `user_id` BIGINT(100) NOT NULL,
  `id_post` BIGINT(100) NOT NULL,
  `proccess_booking_id` INT NOT NULL,
  `payment_id` INT NOT NULL,
  PRIMARY KEY (`id_booking`),
  INDEX `fk_booking_user1_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_booking_post1_idx` (`id_post` ASC) VISIBLE,
  INDEX `fk_booking_proccess_booking1_idx` (`proccess_booking_id` ASC) VISIBLE,
  INDEX `fk_booking_payment1_idx` (`payment_id` ASC) VISIBLE,
  CONSTRAINT `fk_booking_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `SWP_SHT`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_booking_post1`
    FOREIGN KEY (`id_post`)
    REFERENCES `SWP_SHT`.`post` (`id_post`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_booking_proccess_booking1`
    FOREIGN KEY (`proccess_booking_id`)
    REFERENCES `SWP_SHT`.`proccess_booking` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_booking_payment1`
    FOREIGN KEY (`payment_id`)
    REFERENCES `SWP_SHT`.`payment` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
